package com.sharechain.finance.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import org.litepal.crud.DataSupport;

import java.io.Serializable;

/**
 * Entity mapped to table NEWS_CHANNEL_TABLE.
 */
public class NewsChannelTable extends DataSupport implements Serializable {
    public static final int CACHE_TYPE_MINE = 0;
    public static final int CACHE_TYPE_ALL = 1;

    private String newsChannelName;
    private String newsChannelId;
    private boolean newsChannelSelect;
    private Boolean newsChannelFixed;
    private int cacheType;

    public NewsChannelTable() {

    }

    /**
     * Not-null value.
     */
    public String getNewsChannelName() {
        return newsChannelName;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setNewsChannelName(String newsChannelName) {
        this.newsChannelName = newsChannelName;
    }

    /**
     * Not-null value.
     */
    public String getNewsChannelId() {
        return newsChannelId;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setNewsChannelId(String newsChannelId) {
        this.newsChannelId = newsChannelId;
    }

    public boolean getNewsChannelSelect() {
        return newsChannelSelect;
    }

    public void setNewsChannelSelect(boolean newsChannelSelect) {
        this.newsChannelSelect = newsChannelSelect;
    }

    public Boolean getNewsChannelFixed() {
        return newsChannelFixed;
    }

    public void setNewsChannelFixed(Boolean newsChannelFixed) {
        this.newsChannelFixed = newsChannelFixed;
    }

    public int getCacheType() {
        return cacheType;
    }

    public void setCacheType(int cacheType) {
        this.cacheType = cacheType;
    }
}
